### ISSUE TITLE
Add Flutter Desktop support

### ISSUE THREAD

**Issue by dcharkes** [google/webcrypto.dart#22]
Flutter desktop is becoming more common.

We should add support for flutter desktop.

**Comment by epoberezkin** [comment]
I've managed to run `flutter pub run webcrypto:setup` but `dart test` doesn't work, I can only run `flutter test`...

**Comment by WiRight** [comment]
What about MacOS and Windows?

**Comment by rokk4** [comment]
@WiRight I was able to manually add libcrypto as .dylib and it works.
You can run the compilation on MacOS if you install all the deps.

I also tried it for windows, but I don't know shit about compiling BoringSSL/complicated C++ on Windows I could not make it work. 

@dcharkes I think the biggest problem is setting up the build enviroment on windows, which is a pain in the ...  Would it be a possibility to include precompiled BoringSSL? Or is this not a good idea because the user of the lib would then have to trust the precompiled .dll?

**Comment by dcharkes** [comment]
I believe the build re-exports symbols so that they don't collide. Moreover, the build only uses a subset of BoringSSL which is smaller than the full BoringSSL. So, I don't believe we can use a precompiled dylib from BoringSSL directly.

The Windows setup should be very similar to the Linux setup, the builds are both CMake.
The MacOS setup should be very similar to the iOS setup, the builds are both CocoaPods.

**Comment by MichaelPriebe** [comment]
The error that stops the setup script from working on Windows was fixed in https://github.com/google/webcrypto.dart/commit/851ab9975226769c1f1445d292a77462bf616f39, but even with cmake and gcc, the build fails on Windows.

**Comment by jonasfj** [comment]
This is now resolved in version 0.5.4 which supports Android, iOS, Web, Windows, Linux and Mac.
